---
title: "GeoVis"
author: "Huanye Liu"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library, include = F,cache=F,echo=F}
library(readr)
library(haven)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(fiftystater)
library(viridis)
library(maps)
# create sf objects from shape files
library(sf)
library(rvest)
library(devtools)
library(ggrepel)
```


```{r readfile and preprocessing, include = F,cache=F,echo=F}
# use library sf instead of sp to read in world map shape files.
world<-st_read("cshapes/cshapes.shp")%>%
  mutate(CNTRY_NAME=as.character(CNTRY_NAME))

h1b = read.csv("h1b_kaggle.csv",header = T,row.names=1)
H1B = read_csv("h1b.csv")
GDP_perCap <- read.csv("GDP_perCap.csv",header = T)%>%
  tbl_df()%>%
  mutate(Country.Name=as.character(Country.Name))
visa <- read.csv("PERM_Disclosure_Data_FY17.csv",header = T)
permVisa <- visa%>%
  tbl_df()%>%
  select(COUNTRY_OF_CITIZENSHIP,FOREIGN_WORKER_INFO_EDUCATION,EMPLOYER_YR_ESTAB,DECISION_DATE,EMPLOYER_NUM_EMPLOYEES)


```

```{r data, include = F,cache=F,echo=F}
perm<-permVisa %>%
  filter(!is.na(COUNTRY_OF_CITIZENSHIP))%>%
  group_by(COUNTRY_OF_CITIZENSHIP) %>%
  summarise(NUMBER = n()) %>%
  arrange(desc(NUMBER)) %>%
  head(20)%>%
  right_join(permVisa,by="COUNTRY_OF_CITIZENSHIP")%>%
  filter(!is.na(NUMBER))%>%
  mutate(COUNTRY_OF_CITIZENSHIP=str_to_title(COUNTRY_OF_CITIZENSHIP))%>%
  left_join(GDP_perCap,by=c("COUNTRY_OF_CITIZENSHIP"="Country.Name"))%>%
  filter(!is.na(FOREIGN_WORKER_INFO_EDUCATION))%>%
  mutate(isSmall = ifelse(FOREIGN_WORKER_INFO_EDUCATION=='Doctorate',1,0))%>%
  group_by(COUNTRY_OF_CITIZENSHIP,X2016)%>%
  summarise(rDoc = mean(isSmall))%>%
  left_join(world,by=c("COUNTRY_OF_CITIZENSHIP"="CNTRY_NAME"))%>%
  distinct(COUNTRY_OF_CITIZENSHIP,X2016,rDoc,CAPLONG,CAPLAT)%>%
  # delete the first row of another capital of Brazil to keep one row for each country
  slice(1)
```
  
```{r top10,fig.width=10, echo=F}
  ggplot(world)+
    geom_sf(fill="azure3",color='lightgrey')+
    theme_void()+
    geom_point(data = perm,aes(x=CAPLONG,y=CAPLAT,color=as.numeric(X2016)/1000,size=rDoc),alpha=0.5)+
    geom_text_repel(data = perm, aes(x=CAPLONG,y=CAPLAT,label=COUNTRY_OF_CITIZENSHIP),size=3)+
   
    scale_size(range = c(5, 15))+
    theme(
         plot.title= element_text(size=11),
         plot.subtitle = element_text(size=9),
         plot.caption = element_text(size=8),
        legend.text = element_text(size=7),
        legend.title = element_text(size=9),
        legend.position="bottom")+
  labs(
       title="Wealthier countries have higher proportion of Permanent Visa applicants with Doctorate Degree for working in the US",
       subtitle="as shown by the top 20 countries with high US Permanent Visa applications (2017)",
       
       caption = "Data Source: Office of Foreign Labor Certificatio(OFLC), Employment & Training Administration of the U.S. Department of Labor",
       color="GDP per captial(thousand dollars)",
       size ="Proportion of Applicants with Doctorate Degree")


```
            
              
\pagebreak 
                
              
```{r readdata,include = F,cache=F,echo=F}
H1B = read_csv("h1b.csv")
```
```{r usmap,fig.width=8.5,echo=F}
WageDiff<-H1B%>%
  tbl_df()%>%
  select(SOC_CODE,H1B_DEPENDENT,WORKSITE_STATE,WAGE_RATE_OF_PAY_FROM,WAGE_UNIT_OF_PAY)%>%
  filter(!is.na(SOC_CODE)&!is.na(H1B_DEPENDENT)&WAGE_UNIT_OF_PAY=='Year')%>%
  group_by(WORKSITE_STATE,SOC_CODE,H1B_DEPENDENT)%>%
  summarise(wage_median = median(as.numeric(WAGE_RATE_OF_PAY_FROM),na.rm=T))%>%
  spread(H1B_DEPENDENT,wage_median)%>%
  filter(!is.na(Y) & !is.na(N))%>%
  mutate(WagePremium=Y-N)%>%
  group_by(WORKSITE_STATE)%>%
  summarise(AvePremium=mean(WagePremium))%>%
  filter(WORKSITE_STATE %in% state.abb)%>%
  left_join(bind_cols(fname=state.name,abbname=state.abb),by=c("WORKSITE_STATE"="abbname"))%>%
  select(fname,AvePremium)%>%
  mutate(fname=str_to_lower(fname))%>%
  mutate(AvePremium=AvePremium/1000)%>%
  mutate(AvePremium=cut(AvePremium,c(-15,-10,-5,0,5,10,20)))
  
  
data("fifty_states")

ggplot(WageDiff,aes(map_id=fname))+
  geom_map(aes(fill=AvePremium),map=fifty_states)+
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map()+
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  theme_void()+
  theme(plot.title= element_text(size=10),
        plot.subtitle = element_text(size=8),
        plot.caption = element_text(size=8),
        legend.text = element_text(size=7),
        legend.title = element_text(size=8),
        legend.position = c(1,0),
        legend.justification = c(1,0)
        )+
  scale_fill_brewer(palette =  'RdBu')+
  labs(x = "", y = "",
       fill = "wage difference\n(thousand) interval",
       title="H1B Dependent employers proposed lower mean wages than H1B Independent employers in most states of the US (2017)",
       subtitle="\nwage difference = wage(H1B Dependent employers)-wage(H1B Independent employers)",
       caption="Data Source: Office of Foreign Labor Certificatio(OFLC), Employment & Training Administration of the U.S. Department of Labor")
  

  
  
```




