---
title: "Visualizations"
author: "Huanye Liu"
output:
  pdf_document: default
  html_document: default
---


```{r libraries,include = F,cache=F,echo=TRUE}
library(readr)
library(haven)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(maps)
library(viridis)
library(ggrepel)
```
```{r theme, include = F,cache=F,echo=F}
the_theme = theme(
                  #plot.background = element_rect(color="grey50",size=5),
                  panel.background = element_rect(size=2),
                  plot.title= element_text(size=15,vjust=3),
                  plot.subtitle = element_text(size = 13,vjust=2),
                  axis.title.x.bottom = element_text(size=13,margin = margin(t=20,r=0,b=20,l=0)),
                  axis.title.y.left = element_text(size=15,margin = margin(t=0,r=30,b=0,l=20)),
                  axis.text = element_text(size=14),
                  legend.title = element_text(size=12,vjust=1,margin = margin(10,10,10,10)), 
                  legend.text = element_text(size=11,margin = margin(10,10,10,10)),
                  legend.position = "top")
```

```{r readdata, include = F,cache=F,echo=F}
H1B = read_csv("h1b.csv")
```
```{r wage1, fig.width = 12, fig.height=13,echo=F}
industry_code = c("54","51","31","56","62","61","52","44","42","23","72","92")
industry_name =c(
            	"Professional and Technical Services",
               "information",
               "Manufacturing",
               "Administrative and Support",
               "Health Care and Social Assistance",
               "Educational Services",
               "Finance and Insurance",
               "Retail Trade",
               "Wholesale Trade",
               "Construction",
               "Accommodation and Food Services",
               "Public Administration"
)
industry_df = bind_cols(code = industry_code,name = industry_name)
H1B%>%
  filter(!is.na(H1B_DEPENDENT) & WAGE_UNIT_OF_PAY=='Year' & !is.na(WAGE_RATE_OF_PAY_FROM)) %>%
  mutate(industry=str_sub(as.character(NAICS_CODE),1,2))%>%
  mutate(industry=ifelse(industry%in%c("31","32","33"),"31",industry))%>%
  mutate(industry=ifelse(industry%in%c("44","45"),"44",industry))%>%
  mutate(industry=ifelse(industry%in%c("48","49"),"48",industry))%>%
  filter(industry %in% industry_code)%>%
  left_join(industry_df,by=c("industry"="code"))%>%
  mutate(H1B_DEPENDENT = ifelse(H1B_DEPENDENT=="Y","yes","no"))%>%
  rename(`H1B dependent` = H1B_DEPENDENT)%>%
  ggplot(aes(WAGE_RATE_OF_PAY_FROM/1000))+
  geom_density(aes(fill=`H1B dependent`,color=`H1B dependent`),alpha = 0.2,na.rm=T)+
  scale_color_manual(values = c(no ="#4682b4",yes="#E74C3C"))+
  scale_fill_manual(values = c(no ="#4682b4",yes="#E74C3C"))+
  the_theme+
  theme(legend.position = "top")+
  labs(
    x = "wage rate (thousand dollars)",
    caption = "Data Source: Employment & Training Administration of the U.S. Department of Labor\n\n\n\n\n",
    title = "Wages proposed by H1B dependent and independent employers from 12 industries in 2017"
  )+
  xlim(0,400)+
  facet_wrap(~name,ncol = 3,scale = "free")
```
              

\pagebreak    
             
               
```{r wage2, fig.width = 12, fig.height=15,echo=F}
industry_code = c("54","51","31","56","62","61","52","44","42","23","72","92")
industry_name =c(
            	"Professional and Technical Services",
               "information",
               "Manufacturing",
               "Administrative and Support",
               "Health Care and Social Assistance",
               "Educational Services",
               "Finance and Insurance",
               "Retail Trade",
               "Wholesale Trade",
               "Construction",
               "Accommodation and Food Services",
               "Public Administration"
)
industry_df = bind_cols(code = industry_code,name = industry_name)
H1B%>%
  filter(!is.na(H1B_DEPENDENT) & WAGE_UNIT_OF_PAY=='Year' & !is.na(PREVAILING_WAGE)&!is.na(WAGE_RATE_OF_PAY_FROM)) %>%
  mutate(industry=str_sub(as.character(NAICS_CODE),1,2))%>%
  mutate(industry=ifelse(industry%in%c("31","32","33"),"31",industry))%>%
  mutate(industry=ifelse(industry%in%c("44","45"),"44",industry))%>%
  mutate(industry=ifelse(industry%in%c("48","49"),"48",industry))%>%
  filter(industry %in% industry_code)%>%
  left_join(industry_df,by=c("industry"="code"))%>%
  mutate(H1B_DEPENDENT = ifelse(H1B_DEPENDENT=="Y","yes","no"))%>%
  mutate(wage_diff = WAGE_RATE_OF_PAY_FROM-PREVAILING_WAGE) %>%
  filter(!wage_diff==0)%>%
  ggplot(aes(x=H1B_DEPENDENT,y=wage_diff/1000))+
  geom_violin(aes(fill=H1B_DEPENDENT,color=H1B_DEPENDENT),alpha = 0.2,na.rm=T,show.legend = F)+
  scale_color_manual(values = c(no ="#4682b4",yes="#E74C3C"))+
  scale_fill_manual(values = c(no ="#4682b4",yes="#E74C3C"))+
  the_theme+
  labs(
    x = "H1B dependent or not",
    y = "wage premium (thousand dollars)",
    title = "Wage premiums proposed by H1B dependent and independent employers from 12 industries in 2017",
    subtitle = "wage premium = wage proposed by the employer - prevailing wage\n",
    caption = "Data Source: Employment & Training Administration of the U.S. Department of Labor"
  )+
  ylim(-100,250)+
  facet_wrap(~name,ncol = 3,scale = "free")
```
        

        
